### ISSUE TITLE
Cannot compile using Android Studio 2.1.3

### ISSUE THREAD

**Issue by singsingwong2** [wso2/cdmf-agent-android#6]
Just clone the source tree and rebuild the project on Android Studio 2.1.3. But it prompts for the following error:

C:\shared\source\product-mdm\modules\mobile-agents\android\client\client\src\main\java\org\wso2\emm\agent\services\NetworkConnectedReceiver.java
Error:(42, 28) error: cannot find symbol method startServiceAsUser(Intent,UserHandle)
C:\shared\source\product-mdm\modules\mobile-agents\android\client\client\src\main\java\org\wso2\emm\agent\utils\CommonUtils.java
Error:(432, 11) error: cannot find symbol method startServiceAsUser(Intent,UserHandle)
Error:(445, 11) error: cannot find symbol method startServiceAsUser(Intent,UserHandle)
Note: Some input files use or override a deprecated API.

Any idea?

**Comment by charithag** [comment]
You need to have access to android hidden APIs. Please follow instructions in documentation[1]

[1] https://docs.wso2.com/display/IoTS310/White+Labeling+the+WSO2+Android+Agent#WhiteLabelingtheWSO2AndroidAgent-Prerequisites
